version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.9.0
    - 3.9.1
  - dependency-name: rollup
    versions:
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.3
    - 2.42.4
    - 2.44.0
    - 2.45.0
    - 2.45.1
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.13.10
    - 7.13.6
    - 7.13.7
    - 7.13.9
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@trigen/scripts-plugin-eslint"
    versions:
    - 7.0.6
    - 7.3.3
  - dependency-name: "@trigen/scripts-preset-lib"
    versions:
    - 7.0.6
    - 7.3.3
  - dependency-name: "@trigen/scripts-plugin-typescript"
    versions:
    - 7.0.2
  - dependency-name: "@trigen/scripts-plugin-babel"
    versions:
    - 7.0.2
  - dependency-name: "@trigen/scripts-plugin-size-limit"
    versions:
    - 7.0.2
  - dependency-name: "@trigen/scripts-plugin-jest"
    versions:
    - 7.0.2
  - dependency-name: "@trigen/scripts"
    versions:
    - 7.0.2
  - dependency-name: "@trigen/scripts-plugin-rollup"
    versions:
    - 7.0.2
  - dependency-name: "@size-limit/preset-small-lib"
    versions:
    - 4.9.1
