name: CI
on:
  push:
  pull_request:
jobs:
  base-test:
    runs-on: ubuntu-latest
    name: Node.js base test
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run tests
        run: yarn test
      - name: Collect coverage
        uses: coverallsapp/github-action@master
        if: success()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  matrix-test:
    strategy:
      matrix:
        node-version:
          - 12
          - 14
        runs-on:
          - ubuntu-latest
          - macos-latest
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.runs-on }} matrix test
    runs-on: ${{ matrix.runs-on }}
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run tests
        run: yarn test
